### ISSUE TITLE
Clean install throws error: ImportError no module named chardet

### ISSUE THREAD

**Issue by thibmaek** [Evolution0/bandcamp-dl#101]
**Python version:**  3.5.2

**Bandcamp-dl version:** latest from `pip install bandcamp-downloader`

**Bancamp-dl options:**  `-h`

**url:**  none given

**options:**  none given

**Describe the issue:**
-------------------------
Using pyenv with Python 3.5.2 and a clean install with `pip install bandcamp-downloader`, it throws the following error (simply testing with the -h flag):
Traceback (most recent call last):
  File "/Users/thibaultmaekelbergh/.pyenv/versions/3.5.2/lib/python3.5/site-packages/bandcamp_downloader-0.0.7.post6-py3.5.egg/bandcamp_dl/utils/requests_patch.py", line 2, in <module>
ImportError: No module named 'cchardet'

During handling of the above exception, another exception occurred:

```
Traceback (most recent call last):
  File "/Users/thibaultmaekelbergh/.pyenv/versions/3.5.2/bin/bandcamp-dl", line 9, in <module>
    load_entry_point('bandcamp-downloader==0.0.7.post6', 'console_scripts', 'bandcamp-dl')()
  File "/Users/thibaultmaekelbergh/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/thibaultmaekelbergh/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/Users/thibaultmaekelbergh/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/Users/thibaultmaekelbergh/.pyenv/versions/3.5.2/lib/python3.5/site-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/thibaultmaekelbergh/.pyenv/versions/3.5.2/lib/python3.5/site-packages/bandcamp_downloader-0.0.7.post6-py3.5.egg/bandcamp_dl/bandcamp_dl.py", line 50, in <module>
  File "/Users/thibaultmaekelbergh/.pyenv/versions/3.5.2/lib/python3.5/site-packages/bandcamp_downloader-0.0.7.post6-py3.5.egg/bandcamp_dl/bandcampdownloader.py", line 11, in <module>
  File "/Users/thibaultmaekelbergh/.pyenv/versions/3.5.2/lib/python3.5/site-packages/bandcamp_downloader-0.0.7.post6-py3.5.egg/bandcamp_dl/utils/requests_patch.py", line 4, in <module>
ImportError: No module named 'chardet'
```

**Comment by Evolution0** [comment]
Weird, chardet is listed as a requirement, no way should it have not been installed.

Any errors when installing bandcamp-dl to the effect of one of the requirements not getting installed?

**Comment by thibmaek** [comment]
@Evolution0 Here's the output of requirements:
![image](https://cloud.githubusercontent.com/assets/6213695/22718952/74f3af8c-eda3-11e6-8b1b-a31d320c11a0.png)

**Comment by Evolution0** [comment]
Hm, chardet is never installed like it should be, I have it listed just like all the other dependencies.

Interestingly enough this is happening for me as well, only reason I didn't notice is I always run from source and have chardet.

Looks like I need to dig around to find out what might cause this.

**Comment by Evolution0** [comment]
Alright fixed it, when I pushed the changes with the requests monkey-patch using chardet I didn't update the requirements.

There is a fix release on the releases page as well as on PyPI so a simple `pip install --upgrade bandcamp-downloader` should suffice.
