### ISSUE TITLE
Single-track urls fail to download / missing album_title

### ISSUE THREAD

**Issue by greymouser** [Evolution0/bandcamp-dl#106]
**Python version:**  
$ python --version
Python 2.7.13

**Bandcamp-dl version:**
$ bandcamp-dl -v
bandcamp-dl 1.0

**Bancamp-dl options:**  
n/a

**url:**  
https://therealashleypark.bandcamp.com/track/rocket-on-the-highway

**options:**  
n/a

**Describe the issue:**
-------------------------
Many artists have "one off" tracks, instead of full-albums. bandcamp-dl should be able to download from these URLs as well as full-album URLs.

Instead of
  * https://ARTIST.bandcamp.com/album/ALBUMNAME
the URL looks like
 * https://ARTIST.bandcamp.com/track/TRACKNAME

For tracks that *are* part of an album, from their single-track-info URL, using bandcamp-dl works as expected (i.e. for downloading the single track). This is only an issue for tracks that are not part of an album.

```
$ bandcamp-dl https://therealashleypark.bandcamp.com/track/rocket-on-the-highway
Traceback (most recent call last):
  File "/usr/local/bin/bandcamp-dl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/bandcamp_dl/bandcamp_dl.py", line 55, in main
    album = bandcamp.parse(url)
  File "/usr/local/lib/python2.7/site-packages/bandcamp_dl/Bandcamp.py", line 28, in parse
    album_meta = self.extract_album_meta_data(r)
  File "/usr/local/lib/python2.7/site-packages/bandcamp_dl/Bandcamp.py", line 76, in extract_album_meta_data
    album['title'] = embedData['EmbedData']['album_title']
KeyError: 'album_title'
```

**Comment by greymouser** [comment]
... aaaaaand, after upgrading, this is already fixed. Please ignore!
