### ISSUE TITLE
Simple download fails with Python3.6

### ISSUE THREAD

**Issue by JDeanThomas** [Evolution0/bandcamp-dl#113]
**Python version: 3.6

**Bandcamp-dl version: 0.0.7-09

**Bancamp-dl options: none

**url: https://landoftalk.bandcamp.com/album/life-after-youth

**options: none 

**Describe the issue:** (all dependencies are met and current)
-------------------------

MBP:~ jasonthomas$ bandcamp-dl https://landoftalk.bandcamp.com/track/heartcore
Traceback (most recent call last):
  File "/usr/local/bin/bandcamp-dl", line 11, in <module>
    load_entry_point('bandcamp-downloader==0.0.7.post9', 'console_scripts', 'bandcamp-dl')()
  File "/usr/local/Cellar/bandcamp-dl/0.0.7-09/libexec/lib/python3.6/site-packages/bandcamp_dl/__main__.py", line 83, in main
    album = bandcamp.parse(url)
  File "/usr/local/Cellar/bandcamp-dl/0.0.7-09/libexec/lib/python3.6/site-packages/bandcamp_dl/bandcamp.py", line 29, in parse
    bandcamp_json = BandcampJSON(self.soup).generate()
  File "/usr/local/Cellar/bandcamp-dl/0.0.7-09/libexec/lib/python3.6/site-packages/bandcamp_dl/bandcampjson.py", line 20, in generate
    self.js_to_json()
  File "/usr/local/Cellar/bandcamp-dl/0.0.7-09/libexec/lib/python3.6/site-packages/bandcamp_dl/bandcampjson.py", line 43, in js_to_json
    self.get_js()
  File "/usr/local/Cellar/bandcamp-dl/0.0.7-09/libexec/lib/python3.6/site-packages/bandcamp_dl/bandcampjson.py", line 31, in get_js
    self.js_data = self.body.find("script", {"src": False}, text=re.compile(self.target)).string
AttributeError: 'NoneType' object has no attribute 'string'

**Comment by poloba** [comment]
Same issue with python 3.6 and bandcamp-dl 0.0.7-09

**Comment by ryanmcginnis** [comment]
Yeah, unfortunately I can't get this to run at all. Same issue as described.

**Comment by Evolution0** [comment]
Confirmed and there is no obvious reason why this would be happening as I can confirm that the targeted script element is indeed on the page.

Working on this and any other backlogged issues asap.

**Comment by Evolution0** [comment]
Interesting, I get a 403 forbidden on the track page through bandcamp-dl but not in the browser.. I wonder if there is now some kind of protection in place to prevent scrapers..

Edit: Seems its now configured to refused GET requests without a proper user agent. A simple enough fix.
Edit2: They seem to have also done something to the track download urls, they now redirect and even with a proper session requests can't seem to handle it.
Edit3: Requests can't seem to download it but wget can... the heck.
Edit4: Even plain old urllib can download it fine...
Edit5: Of all things a typo.. fixed it new build coming.

**Comment by Evolution0** [comment]
Fixed, new release up.

**Comment by poloba** [comment]
Thanks @Evolution0 !
