### ISSUE TITLE
Fails at runtime, KeyError: '--embed-art'

### ISSUE THREAD

**Issue by ryanmcginnis** [Evolution0/bandcamp-dl#118]
**Python version:**  
3.6.0

**Bandcamp-dl version:**
bandcamp-dl-0.0.8-02.sierra

**Bandcamp-dl options:**  
N/A

**url:**  
N/A

**options:**  
N/A

**Describe the issue:**
1. Install bandcamp-dl under macOS Sierra 10.12.4 using brew install bandcamp-dl
2. Run `bandcamp-dl`
3. Observe the following error:
```
Traceback (most recent call last):
  File "/usr/local/bin/bandcamp-dl", line 11, in <module>
    load_entry_point('bandcamp-downloader==0.0.8.post2', 'console_scripts', 'bandcamp-dl')()
  File "/usr/local/Cellar/bandcamp-dl/0.0.8-02/libexec/lib/python3.6/site-packages/bandcamp_dl/__main__.py", line 100, in main
    arguments['--embed-art'], arguments['--no-slugify'])
KeyError: '--embed-art'
```
4. Run `bandcamp-dl [URL]`; observe identical error
5. Run `bandcamp-dl --embed-art [URL]`; observe identical error

**Comment by Evolution0** [comment]
Any lingering `not.finished` files? If so I would delete them and try again.

Edit:
This issue will no longer happen after my latest release, do a `pip install bandcamp-downloader --upgrade` 😸

**Comment by ryanmcginnis** [comment]
I updated, but now I get this:

    Traceback (most recent call last):
      File "/Library/Frameworks/Python.framework/Versions/2.7/bin/bandcamp-dl", line 7, in <module>
        from bandcamp_dl.bandcamp_dl import main
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-
    packages/bandcamp_dl/bandcamp_dl.py", line 49, in <module>
        from .bandcamp import Bandcamp
      File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-
    packages/bandcamp_dl/bandcamp.py", line 10
        def parse(self, url: str, art: bool=True) -> dict or None:
                           ^
    SyntaxError: invalid syntax

This occurs with `bandcamp-dl` and `bandcamp-dl [URL]`.
