### ISSUE TITLE
Error 

### ISSUE THREAD

**Issue by ghost** [Evolution0/bandcamp-dl#121]
i have writter in terminal pip install sudo pip install bandcamp-downloader
and 

bandcamp-dl

Traceback (most recent call last):
  File "/usr/local/bin/bandcamp-dl", line 7, in <module>
    from bandcamp_dl.bandcamp_dl import main
  File "/usr/local/lib/python2.7/dist-packages/bandcamp_dl/bandcamp_dl.py", line 49, in <module>
    from .bandcamp import Bandcamp
  File "/usr/local/lib/python2.7/dist-packages/bandcamp_dl/bandcamp.py", line 10
    def parse(self, url: str, art: bool=True) -> dict or None:
                       ^
SyntaxError: invalid syntax

**Comment by Evolution0** [comment]
> python2.7

That is your problem. Could have sworn my changes should have prevented people from installing it in versions older than 3.4.. I'll have to look into another way of preventing it being installed under an older version of Python.
