### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by irk3n** [Evolution0/bandcamp-dl#127]
**Python version:**  
Python 2.7.13

**Bandcamp-dl version:**

**Bancamp-dl options:**  
bandcamp-dl --help

**url:**  

**options:**  

**Describe the issue:**
-------------------------
bandcamp-dl -h

Traceback (most recent call last):
  File "/usr/local/bin/bandcamp-dl", line 11, in <module>
    load_entry_point('bandcamp-downloader==0.0.8.post7', 'console_scripts', 'bandcamp-dl')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 561, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2631, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2291, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2297, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "build/bdist.linux-x86_64/egg/bandcamp_dl/__main__.py", line 54, in <module>
  File "/usr/local/lib/python2.7/dist-packages/bandcamp_downloader-0.0.8.post7-py2.7.egg/bandcamp_dl/bandcamp.py", line 17
    def parse(self, url: str, art: bool=True, lyrics: bool=False, debugging: bool=False) -> dict or None:

SyntaxError: invalid syntax

**Comment by Evolution0** [comment]
> Python 2.7.13

There is your problem. Its 3.4 and up.

It only installs under older versions as I can't seem to stop it from doing so.

**Comment by irk3n** [comment]
I resolved with: 
sudo python3 setup.py install

**Comment by Evolution0** [comment]
Yep seems you ran into the issue where Python 3 is installed along with Python 2.

This is less of an issue with bandcamp-dl and more of an issue with the nature of Python installations these days. I still haven't found a way around it other than to tell users to either switch to Python 3 entirely, force Python 3 when installing, or adjust their PATH. :/
