### ISSUE TITLE
Bandcamp-dl fails to run when provided an artist name or link

### ISSUE THREAD

**Issue by HybridAir** [Evolution0/bandcamp-dl#128]
**Python version:**
`Python 3.6.1`

**Bandcamp-dl version:**
`0.0.8-06`

**Bancamp-dl options:**  
`bandcamp-dl --embed-art --artist hkedream -d`
and
`bandcamp-dl --embed-art https://hkedream.bandcamp.com/ -d`

**Describe the issue:**
-------------------------

In both cases the program attemps to start, but fails at varying stages. The not.finished file has been removed after each test. All output and tracebacks are provided below:

```
bandcamp-dl --embed-art --artist hkedream -d
DEBUG:root:
        URL: None
DEBUG:root: Album data:
        None
DEBUG:root:Preparing download process..
DEBUG:root:Initiating download process..
Traceback (most recent call last):
  File "D:\code\Python36\Scripts\bandcamp-dl-script.py", line 11, in <module>
    load_entry_point('bandcamp-downloader==0.0.8.post6', 'console_scripts', 'bandcamp-dl')()
  File "d:\code\python36\lib\site-packages\bandcamp_downloader-0.0.8.post6-py3.6.egg\bandcamp_dl\__main__.py", line 104, in main
  File "d:\code\python36\lib\site-packages\bandcamp_downloader-0.0.8.post6-py3.6.egg\bandcamp_dl\bandcampdownloader.py", line 53, in start
TypeError: 'NoneType' object is not subscriptable
```

```
bandcamp-dl --embed-art https://hkedream.bandcamp.com/ -d
DEBUG:root:
        URL: https://hkedream.bandcamp.com/
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): hkedream.bandcamp.com
DEBUG:requests.packages.urllib3.connectionpool:https://hkedream.bandcamp.com:443 "GET / HTTP/1.1" 200 None
DEBUG:root: Generating BandcampJSON..
DEBUG:root: Grabbing target data..
DEBUG:root: Converting JS to JSON..
DEBUG:root: Grabbing embedded script..
Traceback (most recent call last):
  File "D:\code\Python36\Scripts\bandcamp-dl-script.py", line 11, in <module>
    load_entry_point('bandcamp-downloader==0.0.8.post6', 'console_scripts', 'bandcamp-dl')()
  File "d:\code\python36\lib\site-packages\bandcamp_downloader-0.0.8.post6-py3.6.egg\bandcamp_dl\__main__.py", line 91, in main
  File "d:\code\python36\lib\site-packages\bandcamp_downloader-0.0.8.post6-py3.6.egg\bandcamp_dl\bandcamp.py", line 40, in parse
  File "d:\code\python36\lib\site-packages\bandcamp_downloader-0.0.8.post6-py3.6.egg\bandcamp_dl\bandcampjson.py", line 25, in generate
  File "d:\code\python36\lib\site-packages\bandcamp_downloader-0.0.8.post6-py3.6.egg\bandcamp_dl\bandcampjson.py", line 50, in js_to_json
  File "d:\code\python36\lib\site-packages\bandcamp_downloader-0.0.8.post6-py3.6.egg\bandcamp_dl\bandcampjson.py", line 38, in get_js
  File "d:\code\python36\lib\site-packages\bandcamp_downloader-0.0.8.post6-py3.6.egg\bandcamp_dl\bandcampjson.py", line 45, in extract_data
AttributeError: 'NoneType' object has no attribute 'group'
```

**Comment by Evolution0** [comment]
So in the first case the url is never properly generated and in the second case its failing to extract the needed data from the js..

I'll look into it.

**Comment by Evolution0** [comment]
Ah I should have read slower, seems you are trying to use the `--artist` option without providing the album name `--artist` is always required when using `--track` and `--album` but it can't be used by itself.

Discography downloading isn't in yet but I do plan to add it at some point.

Edit: Or its the artist itself that is weird, as providing even a track/album name seems to fail as well.

**Comment by HybridAir** [comment]
Ah I understand, thank you for looking into it!

**Comment by Evolution0** [comment]
Seems I may still need to look into it, its not acting as it should even using the correct commands. Not sure if something has changed with Bandcamp or just a quirk of the artists pages messing it up.

**Comment by HybridAir** [comment]
I just tried it with a different artist/album (https://weareallastronauts.bandcamp.com/album/elysium), using the command `bandcamp-dl --embed-art --artist weareallastronauts --album elysium -d`. The first attempt failed with the following output:

```
DEBUG:root:
        URL: None
DEBUG:root: Album data:
        None
DEBUG:root:Preparing download process..
DEBUG:root:Initiating download process..
Traceback (most recent call last):
  File "D:\code\Python36\Scripts\bandcamp-dl-script.py", line 11, in <module>
    load_entry_point('bandcamp-downloader==0.0.8.post6', 'console_scripts', 'bandcamp-dl')()
  File "d:\code\python36\lib\site-packages\bandcamp_downloader-0.0.8.post6-py3.6.egg\bandcamp_dl\__main__.py", line 104, in main
  File "d:\code\python36\lib\site-packages\bandcamp_downloader-0.0.8.post6-py3.6.egg\bandcamp_dl\bandcampdownloader.py", line 53, in start
TypeError: 'NoneType' object is not subscriptable
```

All attempts after the above happened appeared to work as expected:

```
DEBUG:root:
        URL: http://weareallastronauts.bandcamp.com/album/elysium
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): weareallastronauts.bandcamp.com
DEBUG:requests.packages.urllib3.connectionpool:http://weareallastronauts.bandcamp.com:80 "GET /album/elysium HTTP/1.1" 301 None
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): weareallastronauts.bandcamp.com
DEBUG:requests.packages.urllib3.connectionpool:https://weareallastronauts.bandcamp.com:443 "GET /album/elysium HTTP/1.1" 200 None
DEBUG:root: Generating BandcampJSON..
DEBUG:root: Grabbing target data..
DEBUG:root: Converting JS to JSON..
DEBUG:root: Grabbing embedded script..
DEBUG:root: Grabbing target data..
DEBUG:root: Converting JS to JSON..
DEBUG:root: Grabbing embedded script..
DEBUG:root: BandcampJSON generated..
DEBUG:root: Generating Album..
DEBUG:root: Generating track metadata..
DEBUG:root: Track metadata generated..
DEBUG:root: Generating track metadata..
DEBUG:root: Track metadata generated..
DEBUG:root: Album generated..
DEBUG:root: Album data:
        {'tracks': [{'duration': 284.651, 'track': '1', 'title': 'Elysium (Part I)', 'url': 'http://popplers5.bandcamp.com/download/track?enc=mp3-128&fsig=44641fc04dcb2a2f5a6eab0d5e3d0de9&id=963667615&stream=1&ts=1498958182.0'}, {'duration': 170.233, 'track': '2', 'title': 'Elysium (Part II)', 'url': 'http://popplers5.bandcamp.com/download/track?enc=mp3-128&fsig=9311b806d72f7caf1da5cc949e720ea9&id=1226985514&stream=1&ts=1498958182.0'}], 'title': 'Elysium', 'artist': 'We Are All Astronauts', 'label': 'We Are All Astronauts', 'full': True, 'art': 'https://f4.bcbits.com/img/a2398476725_16.jpg', 'date': '2017'}
DEBUG:root:Preparing download process..
DEBUG:root:Initiating download process..
DEBUG:root: Generating filepath/trackname..
DEBUG:root: filepath/trackname generated..
DEBUG:root:
        Path: D:\Blake\Desktop\bandcampdl/we-are-all-astronauts/elysium/01 - elysium-part-i.mp3
DEBUG:root: Directory:
        D:\Blake\Desktop\bandcampdl/we-are-all-astronauts/elysium
DEBUG:root: Directory doesn't exist, creating..
DEBUG:root: Current file:
        D:\Blake\Desktop\bandcampdl/we-are-all-astronauts/elysium/01 - elysium-part-i.mp3.tmp
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTPS connection (1): f4.bcbits.com
DEBUG:requests.packages.urllib3.connectionpool:https://f4.bcbits.com:443 "GET /img/a2398476725_16.jpg HTTP/1.1" 200 40401
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): popplers5.bandcamp.com
DEBUG:requests.packages.urllib3.connectionpool:http://popplers5.bandcamp.com:80 "GET /download/track?enc=mp3-128&fsig=44641fc04dcb2a2f5a6eab0d5e3d0de9&id=963667615&stream=1&ts=1498958182.0 HTTP/1.1" 302 0
DEBUG:requests.packages.urllib3.connectionpool:Starting new HTTP connection (1): p4.bcbits.com
DEBUG:requests.packages.urllib3.connectionpool:http://p4.bcbits.com:80 "GET /download/track/dacea04d9b65e1163ba5c8904d7b15fd/mp3-128/963667615?fsig=f7ab7a73fe9e6e138f50d8eba15c8e08&id=963667615&stream=1&ts=1500091200.0&token=1500091260_06ca9b748ae46e1e0ea444e14c55e16a8e34ad61 HTTP/1.1" 200 4613714
DEBUG:root: Encoding process starting..
DEBUG:root: Encoding process finished..
DEBUG:root: Renaming:
        D:\Blake\Desktop\bandcampdl/we-are-all-astronauts/elysium/01 - elysium-part-i.mp3.tmp -to-> D:\Blake\Desktop\bandcampdl/we-are-all-astronauts/elysium/01 - elysium-part-i.mp3
DEBUG:root: Generating filepath/trackname..
DEBUG:root: filepath/trackname generated..
DEBUG:root:
        Path: D:\Blake\Desktop\bandcampdl/we-are-all-astronauts/elysium/02 - elysium-part-ii.mp3
DEBUG:root: Directory:
        D:\Blake\Desktop\bandcampdl/we-are-all-astronauts/elysium
DEBUG:root: Directory doesn't exist, creating..
DEBUG:root: Current file:
        D:\Blake\Desktop\bandcampdl/we-are-all-astronauts/elysium/02 - elysium-part-ii.mp3.tmp
DEBUG:requests.packages.urllib3.connectionpool:http://popplers5.bandcamp.com:80 "GET /download/track?enc=mp3-128&fsig=9311b806d72f7caf1da5cc949e720ea9&id=1226985514&stream=1&ts=1498958182.0 HTTP/1.1" 302 0
DEBUG:requests.packages.urllib3.connectionpool:http://p4.bcbits.com:80 "GET /download/track/f01038a44efca40ea2ca1428a2e17a6b/mp3-128/1226985514?fsig=b8191fe930615dde370dd57fbcd8052f&id=1226985514&stream=1&ts=1500091200.0&token=1500091260_d8b22813b4fe24c4b724c99e55f4fa724ad5e86b HTTP/1.1" 200 2724674
DEBUG:root: Encoding process starting..
DEBUG:root: Encoding process finished..
DEBUG:root: Renaming:
        D:\Blake\Desktop\bandcampdl/we-are-all-astronauts/elysium/02 - elysium-part-ii.mp3.tmp -to-> D:\Blake\Desktop\bandcampdl/we-are-all-astronauts/elysium/02 - elysium-part-ii.mp3
```

**Comment by Evolution0** [comment]
So simply running the same command again (The above one) worked after the first failed?

**Comment by HybridAir** [comment]
Yes. Just tried again, and it worked the first time now.

**Comment by Evolution0** [comment]
It did it with the first commands in the initial report (In which not working was expected behavior) but all commands after that have worked fine for me.

Id assume there was a leftover not.finished file in the directory from the failed commands and it was preventing subsequent commands from working as I tested running the original commands that aren't meant to work and it did indeed create a not.finished file which prevented all commands run from that directory to fail afterwords (and removing it made everything work again)

So while it wasn't as major a bug as I thought this may be it still brings up something I should have fixed ages ago, making sure the not.finished file only gets created when it absolutely should and deleting it properly when done (as @Nzen fixed recently)

Now I just need to make `--artist` require either `--track` or `--album` when used until discography downloading is in. --note to self
