### ISSUE TITLE
Not Working anymore?

### ISSUE THREAD

**Issue by ghost** [Evolution0/bandcamp-dl#131]
**Python version:**  
2.7.12
**Bandcamp-dl version:**
0.0.6-01
**Bancamp-dl options:**  
????
**url:**  

**options:**  

**Describe the issue:**

C:\Users\admin\Music\bandcamp>bandcamp_dl.py https://virginbabylonrecords.bandca
mp.com/album/laideronnette
Traceback (most recent call last):
  File "C:\Users\admin\Music\bandcamp\bandcamp_dl.py", line 75, in <module>
    main()
  File "C:\Users\admin\Music\bandcamp\bandcamp_dl.py", line 63, in main
    album = bandcamp.parse(url)
  File "C:\Users\admin\Music\bandcamp\bandcamp.py", line 9, in parse
    r = requests.get(url)
  File "C:\Python27\lib\site-packages\requests\api.py", line 70, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Python27\lib\site-packages\requests\api.py", line 56, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 488, in reques
t
    resp = self.send(prep, **send_kwargs)
  File "C:\Python27\lib\site-packages\requests\sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "C:\Python27\lib\site-packages\requests\adapters.py", line 485, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='virginbabylonrecords.b
andcamp.com', port=443): Max retries exceeded with url: /album/laideronnette (Ca
used by ProxyError('Cannot connect to proxy.', NewConnectionError('<requests.pac
kages.urllib3.connection.VerifiedHTTPSConnection object at 0x027D5510>: Failed t
o establish a new connection: [Errno 11004] getaddrinfo failed',)))

I've turned off my proxy and i get the same error. Any other ideas?
-------------------------

**Comment by itspull** [comment]
test

**Comment by Evolution0** [comment]
There was a change awhile back on Bandcamp itself that changed the way requests needed to be made, all old versions before this change will no longer work due to this unfortunately without changes.

You can either update to a new version of Python and grab the latest version or make the needed changes to the old version yourself to get it working (Requests need a valid User Agent if I remember correctly)
