### ISSUE TITLE
How i can run with python3

### ISSUE THREAD

**Issue by bizzlerulez** [Evolution0/bandcamp-dl#155]
When I tried to download album its gave me this error code:

Traceback (most recent call last):
  File "c:\python27\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python27\Scripts\bandcamp-dl.exe\__main__.py", line 5, in <module>
  File "c:\python27\lib\site-packages\bandcamp_dl\bandcamp_dl.py", line 49, in <module>
    from .bandcamp import Bandcamp
  File "c:\python27\lib\site-packages\bandcamp_dl\bandcamp.py", line 10
    def parse(self, url: str, art: bool=True) -> dict or None:
                       ^
SyntaxError: invalid syntax
-------------------------
i downloaded program with pip and pip3 both of them. i think its trying to run program witch python 2.7 how can i run program with python 3?

**Comment by Evolution0** [comment]
Uninstall it from Python 2.7.x, its likely first in your path so its trying to use the wrong one.
