### ISSUE TITLE
Failing on everything as of today

### ISSUE THREAD

**Issue by mrgooge** [Evolution0/bandcamp-dl#166]
**Python version:**  
3.8
**Bandcamp-dl version:**
latest
**Bancamp-dl options:**  
just used -d to see debug, tried with no options same result
**url:**  
https://antime.bandcamp.com/album/sonic-healing
NOTE: It's happening on ALL URL's from BC
**options:**  

**Describe the issue:**
-------------------------
get this error (this is DEBUG) on everything I tried to download (worked fine two days ago and before that...Here's an example of the error:

bandcamp-dl -d https://antime.bandcamp.com/album/sonic-healing
DEBUG:root:
	URL: https://antime.bandcamp.com/album/sonic-healing
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): antime.bandcamp.com
DEBUG:urllib3.connectionpool:https://antime.bandcamp.com:443 "GET /album/sonic-healing HTTP/1.1" 200 None
DEBUG:root: Generating BandcampJSON..
DEBUG:root: Grabbing target data..
DEBUG:root: Converting JS to JSON..
DEBUG:root: Grabbing embedded script..
Traceback (most recent call last):
  File "/usr/local/bin/bandcamp-dl", line 11, in <module>
    load_entry_point('bandcamp-downloader==0.0.8.post12', 'console_scripts', 'bandcamp-dl')()
  File "/usr/local/Cellar/bandcamp-dl/0.0.8-12_3/libexec/lib/python3.8/site-packages/bandcamp_dl/__main__.py", line 93, in main
    album = bandcamp.parse(url, True, arguments['--embed-lyrics'], arguments['--debug'])
  File "/usr/local/Cellar/bandcamp-dl/0.0.8-12_3/libexec/lib/python3.8/site-packages/bandcamp_dl/bandcamp.py", line 40, in parse
    bandcamp_json = BandcampJSON(self.soup, debugging).generate()
  File "/usr/local/Cellar/bandcamp-dl/0.0.8-12_3/libexec/lib/python3.8/site-packages/bandcamp_dl/bandcampjson.py", line 25, in generate
    self.js_to_json()
  File "/usr/local/Cellar/bandcamp-dl/0.0.8-12_3/libexec/lib/python3.8/site-packages/bandcamp_dl/bandcampjson.py", line 50, in js_to_json
    self.get_js()
  File "/usr/local/Cellar/bandcamp-dl/0.0.8-12_3/libexec/lib/python3.8/site-packages/bandcamp_dl/bandcampjson.py", line 37, in get_js
    self.js_data = self.body.find("script", {"src": False}, text=re.compile(self.target)).string
AttributeError: 'NoneType' object has no attribute 'string'

**Comment by alex-turavec** [comment]
Try to download any album and receive this message:

PS E:\downloads> bandcamp-dl https://alexyarmak.bandcamp.com/album/synthwave-deconstructed-2
Traceback (most recent call last):
  File "C:\Users\impru\AppData\Local\Programs\Python\Python37-32\Scripts\bandcamp-dl-script.py", line 11, in <module>
    load_entry_point('bandcamp-downloader==0.0.9.dev0', 'console_scripts', 'bandcamp-dl')()
  File "C:\Users\impru\AppData\Local\Programs\Python\Python37-32\lib\site-packages\bandcamp_downloader-0.0.9.dev0-py3.7.egg\bandcamp_dl\__main__.py", line 93, in main
  File "C:\Users\impru\AppData\Local\Programs\Python\Python37-32\lib\site-packages\bandcamp_downloader-0.0.9.dev0-py3.7.egg\bandcamp_dl\bandcamp.py", line 40, in parse
  File "C:\Users\impru\AppData\Local\Programs\Python\Python37-32\lib\site-packages\bandcamp_downloader-0.0.9.dev0-py3.7.egg\bandcamp_dl\bandcampjson.py", line 25, in generate
  File "C:\Users\impru\AppData\Local\Programs\Python\Python37-32\lib\site-packages\bandcamp_downloader-0.0.9.dev0-py3.7.egg\bandcamp_dl\bandcampjson.py", line 50, in js_to_json
  File "C:\Users\impru\AppData\Local\Programs\Python\Python37-32\lib\site-packages\bandcamp_downloader-0.0.9.dev0-py3.7.egg\bandcamp_dl\bandcampjson.py", line 37, in get_js
AttributeError: 'NoneType' object has no attribute 'string'

**Comment by RisingThumb** [comment]
This issue is also happening on my end as well. Python version 3.8.5, and latest bandcamp-dl version.
```
bandcamp-dl -d "https://palm84.bandcamp.com/album/almost-born"
DEBUG:root:
    URL: https://palm84.bandcamp.com/album/almost-born
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): palm84.bandcamp.com:443
DEBUG:urllib3.connectionpool:https://palm84.bandcamp.com:443 "GET /album/almost-born HTTP/1.1" 200 None
DEBUG:root: Generating BandcampJSON..
DEBUG:root: Grabbing target data..
DEBUG:root: Converting JS to JSON..
DEBUG:root: Grabbing embedded script..
Traceback (most recent call last):
  File "/home/odst/.local/bin//bandcamp-dl", line 8, in <module>
    sys.exit(main())
  File "/home/odst/.local/lib/python3.8/site-packages/bandcamp_dl/__main__.py", line 93, in main
    album = bandcamp.parse(url, True, arguments['--embed-lyrics'], arguments['--debug'])
  File "/home/odst/.local/lib/python3.8/site-packages/bandcamp_dl/bandcamp.py", line 40, in parse
    bandcamp_json = BandcampJSON(self.soup, debugging).generate()
  File "/home/odst/.local/lib/python3.8/site-packages/bandcamp_dl/bandcampjson.py", line 25, in generate
    self.js_to_json()
  File "/home/odst/.local/lib/python3.8/site-packages/bandcamp_dl/bandcampjson.py", line 50, in js_to_json
    self.get_js()
  File "/home/odst/.local/lib/python3.8/site-packages/bandcamp_dl/bandcampjson.py", line 37, in get_js
    self.js_data = self.body.find("script", {"src": False}, text=re.compile(self.target)).string
AttributeError: 'NoneType' object has no attribute 'string'
```
Edit:
A file is generated in the directory the command is made under the name "0.0.8-12.not.finished", but not sure how relevant it is to this issue.
```
{'--album': None, '--artist': None, '--base-dir': None, '--debug': True, '--embed-art': False, '--embed-lyrics': False, '--full-album': False, '--group': False, '--help': False, '--no-art': False, '--no-slugify': False, '--overwrite': False, '--template': '%{artist}/%{album}/%{track} - %{title}', '--track': None, '--version': False, 'URL': 'https://palm84.bandcamp.com/album/almost-born'}
```

**Comment by strfox** [comment]
Having this issue as well with bandcamp-dl 0.0.8-12.

```
$ bandcamp-dl -d https://radicaldreamland.bandcamp.com/album/celeste-original-soundtrack
DEBUG:root:
	URL: https://radicaldreamland.bandcamp.com/album/celeste-original-soundtrack
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): radicaldreamland.bandcamp.com:443
DEBUG:urllib3.connectionpool:https://radicaldreamland.bandcamp.com:443 "GET /album/celeste-original-soundtrack HTTP/1.1" 200 None
DEBUG:root: Generating BandcampJSON..
DEBUG:root: Grabbing target data..
DEBUG:root: Converting JS to JSON..
DEBUG:root: Grabbing embedded script..
Traceback (most recent call last):
  File "/home/michel/.local/bin/bandcamp-dl", line 8, in <module>
    sys.exit(main())
  File "/home/michel/.local/lib/python3.8/site-packages/bandcamp_dl/__main__.py", line 93, in main
    album = bandcamp.parse(url, True, arguments['--embed-lyrics'], arguments['--debug'])
  File "/home/michel/.local/lib/python3.8/site-packages/bandcamp_dl/bandcamp.py", line 40, in parse
    bandcamp_json = BandcampJSON(self.soup, debugging).generate()
  File "/home/michel/.local/lib/python3.8/site-packages/bandcamp_dl/bandcampjson.py", line 25, in generate
    self.js_to_json()
  File "/home/michel/.local/lib/python3.8/site-packages/bandcamp_dl/bandcampjson.py", line 50, in js_to_json
    self.get_js()
  File "/home/michel/.local/lib/python3.8/site-packages/bandcamp_dl/bandcampjson.py", line 37, in get_js
    self.js_data = self.body.find("script", {"src": False}, text=re.compile(self.target)).string
AttributeError: 'NoneType' object has no attribute 'string'
```

**Comment by carlos-echeverria** [comment]
I can confirm, I also get exactly a similar error (not exactly the same as above) for any link that i try to get.
Using **Python 3.8.5**, **bandcampc-dl v.0.0.8-12**.

```
% bandcamp-dl -d -r https://gnartapes.bandcamp.com/album/gnarcotics-unanimous
DEBUG:root:
	URL: https://gnartapes.bandcamp.com/album/gnarcotics-unanimous
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): gnartapes.bandcamp.com
DEBUG:urllib3.connectionpool:https://gnartapes.bandcamp.com:443 "GET /album/gnarcotics-unanimous HTTP/1.1" 200 None
DEBUG:root: Generating BandcampJSON..
DEBUG:root: Grabbing target data..
DEBUG:root: Converting JS to JSON..
DEBUG:root: Grabbing embedded script..
Traceback (most recent call last):
  File "/usr/local/bin/bandcamp-dl", line 11, in <module>
    load_entry_point('bandcamp-downloader==0.0.8.post12', 'console_scripts', 'bandcamp-dl')()
  File "/usr/local/Cellar/bandcamp-dl/0.0.8-12_3/libexec/lib/python3.8/site-packages/bandcamp_dl/__main__.py", line 93, in main
    album = bandcamp.parse(url, True, arguments['--embed-lyrics'], arguments['--debug'])
  File "/usr/local/Cellar/bandcamp-dl/0.0.8-12_3/libexec/lib/python3.8/site-packages/bandcamp_dl/bandcamp.py", line 40, in parse
    bandcamp_json = BandcampJSON(self.soup, debugging).generate()
  File "/usr/local/Cellar/bandcamp-dl/0.0.8-12_3/libexec/lib/python3.8/site-packages/bandcamp_dl/bandcampjson.py", line 25, in generate
    self.js_to_json()
  File "/usr/local/Cellar/bandcamp-dl/0.0.8-12_3/libexec/lib/python3.8/site-packages/bandcamp_dl/bandcampjson.py", line 50, in js_to_json
    self.get_js()
  File "/usr/local/Cellar/bandcamp-dl/0.0.8-12_3/libexec/lib/python3.8/site-packages/bandcamp_dl/bandcampjson.py", line 37, in get_js
    self.js_data = self.body.find("script", {"src": False}, text=re.compile(self.target)).string
AttributeError: 'NoneType' object has no attribute 'string'
```
I will continue with the feeling of cold-turkey until its fixed, so please help!!!

**Comment by mrgooge** [comment]
Not a Python programmer, but, I have a feeling that "**AttributeError: 'NoneType' object has no attribute 'string**'"  probably means Bandcamp changed something on their end. It seems the artist or title, or maybe any value is just not working.

**Comment by ppatrzyk** [comment]
@mrgooge yes that's the problem. I fixed that myself and opened a PR. If you need something that works now you can install my fork with `pip install https://github.com/ppatrzyk/bandcamp-dl/archive/jsdatafix.zip`

**Comment by mrgooge** [comment]
Thank you **ppatrzyk**!

**Comment by anarchotaoist** [comment]
> pip install https://github.com/ppatrzyk/bandcamp-dl/archive/jsdatafix.zip

Thanks!

**Comment by ChrysthianChrisley** [comment]
> @mrgooge yes that's the problem. I fixed that myself and opened a PR. If you need something that works now you can install my fork with `pip install https://github.com/ppatrzyk/bandcamp-dl/archive/jsdatafix.zip`

Thanks!

**Comment by RisingThumb** [comment]
Awesome, cheers friend!

**Comment by rien333** [comment]
@All yall: One thank you is enough, after that just heart react or something. Great ettiquette if you don't want to clog the inbox of peeps actually waiting to get this fixed

**Comment by Evolution0** [comment]
Or just use reactions :)

Thanks @ppatrzyk for the fix, merged.

**Comment by jemc** [comment]
Can we get a new release of the main pip package that has this fix, so that people don't need to install from a GitHub URL?
