### ISSUE TITLE
download always fail

### ISSUE THREAD

**Issue by rapha8l** [Evolution0/bandcamp-dl#169]
**Python version:**  
Python 3.8.5

**Bandcamp-dl version:**
0.0.8-12

-------------------------
Hi, since a few  python updates, bandcamp-dl fails on any page with : 

```
Traceback (most recent call last):
  File "/usr/sbin/bandcamp-dl", line 8, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/bandcamp_dl/__main__.py", line 93, in main
    album = bandcamp.parse(url, True, arguments['--embed-lyrics'], arguments['--debug'])
  File "/usr/lib/python3.8/site-packages/bandcamp_dl/bandcamp.py", line 40, in parse
    bandcamp_json = BandcampJSON(self.soup, debugging).generate()
  File "/usr/lib/python3.8/site-packages/bandcamp_dl/bandcampjson.py", line 25, in generate
    self.js_to_json()
  File "/usr/lib/python3.8/site-packages/bandcamp_dl/bandcampjson.py", line 50, in js_to_json
    self.get_js()
  File "/usr/lib/python3.8/site-packages/bandcamp_dl/bandcampjson.py", line 37, in get_js
    self.js_data = self.body.find("script", {"src": False}, text=re.compile(self.target)).string
AttributeError: 'NoneType' object has no attribute 'string'

```

Thanks for you work !

**Comment by mendes-davi** [comment]
Already fixed in the master branch. Install from the repository. Check #168 for further information

**Comment by rapha8l** [comment]
Thanks !
