### ISSUE TITLE
bandcamp-dl failing (again?)

### ISSUE THREAD

**Issue by mrgooge** [Evolution0/bandcamp-dl#170]
**Python version:**  
python@3.8
**Bandcamp-dl version:**
0.0.8-12_4
**Bancamp-dl options:**  

**url:**  
(all url's:
**options:**  
none-
**Describe the issue:**
get failure below

-------------------------
bandcamp-dl https://kinggizzard.bandcamp.com/album/demos-vol-1-vol-2
Traceback (most recent call last):
  File "./bandcamp-dl", line 33, in <module>
    sys.exit(load_entry_point('bandcamp-downloader==0.0.9.post1', 'console_scripts', 'bandcamp-dl')())
  File "/usr/local/Cellar/bandcamp-dl/0.0.8-12_4/libexec/lib/python3.8/site-packages/bandcamp_dl/__main__.py", line 93, in main
    album = bandcamp.parse(url, True, arguments['--embed-lyrics'], arguments['--debug'])
  File "/usr/local/Cellar/bandcamp-dl/0.0.8-12_4/libexec/lib/python3.8/site-packages/bandcamp_dl/bandcamp.py", line 40, in parse
    bandcamp_json = BandcampJSON(self.soup, debugging).generate()
  File "/usr/local/Cellar/bandcamp-dl/0.0.8-12_4/libexec/lib/python3.8/site-packages/bandcamp_dl/bandcampjson.py", line 18, in generate
    self.get_js()
  File "/usr/local/Cellar/bandcamp-dl/0.0.8-12_4/libexec/lib/python3.8/site-packages/bandcamp_dl/bandcampjson.py", line 29, in get_js
    embedded_scripts_raw = [self.body.find("script", {"type": "application/json+ld"}).string]
AttributeError: 'NoneType' object has no attribute 'string'

**Comment by Masterchef365** [comment]
Same issue here, also I like your music taste!

**Comment by mrgooge** [comment]
Thanks Nightdavisao, your fix worked for me!
