### ISSUE TITLE
Script failing on Ubuntu 20.04.

### ISSUE THREAD

**Issue by john302** [Evolution0/bandcamp-dl#172]
Python 2.7.18rc1

bandcamp-dl 0.0.9-01

**Bancamp-dl options:**  None.

https://svartsinn.bandcamp.com/album/vand-d

None

**Describe the issue:**
-------------------------

I get this using the version I got off the Github and installed with python setup.py install. This script is not working with newer Python releases. The file it tells me is not working does not even exist.

`bandcamp-dl https://svartsinn.bandcamp.com/album/vand-d
Traceback (most recent call last):
  File "/usr/local/bin/bandcamp-dl", line 11, in <module>
    load_entry_point('bandcamp-downloader==0.0.9.post1', 'console_scripts', 'bandcamp-dl')()
  File "/usr/local/lib/python3.8/dist-packages/bandcamp_downloader-0.0.9.post1-py3.8.egg/bandcamp_dl/__main__.py", line 92, in main
  File "/usr/local/lib/python3.8/dist-packages/bandcamp_downloader-0.0.9.post1-py3.8.egg/bandcamp_dl/bandcamp.py", line 40, in parse
  File "/usr/local/lib/python3.8/dist-packages/bandcamp_downloader-0.0.9.post1-py3.8.egg/bandcamp_dl/bandcampjson.py", line 18, in generate
  File "/usr/local/lib/python3.8/dist-packages/bandcamp_downloader-0.0.9.post1-py3.8.egg/bandcamp_dl/bandcampjson.py", line 29, in get_js
AttributeError: 'NoneType' object has no attribute 'string'`

**Comment by superjamie** [comment]
This is fixed by PR https://github.com/iheanyi/bandcamp-dl/pull/171

**Comment by Evolution0** [comment]
Fixed in #171
