### ISSUE TITLE
Script does not work 

### ISSUE THREAD

**Issue by LeRatierBretonnien** [Evolution0/bandcamp-dl#173]
**Python version:**  
Python 3.7

**Bandcamp-dl version:**
0.0.0.post1

**Bancamp-dl options:**  
None

**url:**  
bandcamp-dl https://fief.bandcamp.com/album/iii

**options:**  

**Describe the issue:**
Failing, tested with various URL : 

Traceback (most recent call last):
  File "/usr/local/bin/bandcamp-dl", line 11, in <module>
    load_entry_point('bandcamp-downloader==0.0.9.post1', 'console_scripts', 'bandcamp-dl')()
  File "/usr/local/lib/python3.8/site-packages/bandcamp_downloader-0.0.9.post1-py3.8.egg/bandcamp_dl/__main__.py", line 92, in main
  File "/usr/local/lib/python3.8/site-packages/bandcamp_downloader-0.0.9.post1-py3.8.egg/bandcamp_dl/bandcamp.py", line 40, in parse
  File "/usr/local/lib/python3.8/site-packages/bandcamp_downloader-0.0.9.post1-py3.8.egg/bandcamp_dl/bandcampjson.py", line 18, in generate
  File "/usr/local/lib/python3.8/site-packages/bandcamp_downloader-0.0.9.post1-py3.8.egg/bandcamp_dl/bandcampjson.py", line 29, in get_js

-------------------------

**Comment by ChrysthianChrisley** [comment]
Change : 
embedded_scripts_raw = [self.body.find("script", {"type": "application/json+ld"}).string]
To:
embedded_scripts_raw = [self.body.find("script", {"type": "application/ld+json"}).string]

line 29:
bandcamp_dl/bandcampjson.py

**Comment by anarchotaoist** [comment]
> Change :
> embedded_scripts_raw = [self.body.find("script", {"type": "application/json+ld"}).string]
> To:
> embedded_scripts_raw = [self.body.find("script", {"type": "application/ld+json"}).string]
> 
> line 29:
> bandcamp_dl/bandcampjson.py

I cannot find these lines in bandcampjson.py.

**Comment by subokita** [comment]
Same thing is happening to me, there's a pull request that seems to try to fix this issue:

https://github.com/iheanyi/bandcamp-dl/pull/171

**Comment by Evolution0** [comment]
Fixed in #171
