### ISSUE TITLE
Error running the script

### ISSUE THREAD

**Issue by nrlquaker** [Evolution0/bandcamp-dl#190]
**Describe the bug**
After running the script get an error `FileNotFoundError: [Errno 2] No such file or directory: '/Users/vasyl.ustynov/Downloads/0.0.9-01.not.finished'`.

**To Reproduce**
Command to reproduce the behavior:
`bandcamp-dl` or `bandcamp-dl https://ulvegr.bandcamp.com/album/isblod`
```
https://ulvegr.bandcamp.com/album/isblod
```

**Expected behavior**
Script starts downloading.

**Logs**
Most if not always you will get some kind of output explaining the issue, post it:
```
Traceback (most recent call last):
  File "/opt/homebrew/bin/bandcamp-dl", line 33, in <module>
    sys.exit(load_entry_point('bandcamp-downloader==0.0.9.post1', 'console_scripts', 'bandcamp-dl')())
  File "/opt/homebrew/Cellar/bandcamp-dl/0.0.8-12_6/libexec/lib/python3.9/site-packages/bandcamp_dl/__main__.py", line 74, in main
    with open(session_file, "w") as f:
FileNotFoundError: [Errno 2] No such file or directory: '/Users/vasyl.ustynov/Downloads/0.0.9-01.not.finished'
```
If possible after running the command with the --debug option.

**Desktop (please complete the following information):**
 - OS: Mac
 - Version: Monterey 12.0.1.
 - Python: 3.9

**Comment by 89z** [comment]
If youre interested, I have an alternative tool that works:

~~~
PS C:\> bandcamp -i https://ulvegr.bandcamp.com/album/isblod
{Track_Num:1 Title:Jotuntre Streaming_URL:{MP3_128:https://bandcamp.com/stream_redirect?enc=mp3-128&track_id=1462305129&ts=1637675618&t=31acb027db56a60fbf595b6bc6eef5deb12dd08d}}
{Track_Num:2 Title:Dodt Morke Streaming_URL:{MP3_128:https://bandcamp.com/stream_redirect?enc=mp3-128&track_id=2243251463&ts=1637675618&t=6a1c9604207cbe3a2e909bbc6759c24a89e94975}}
{Track_Num:3 Title:Vargold Streaming_URL:{MP3_128:https://bandcamp.com/stream_redirect?enc=mp3-128&track_id=2242214755&ts=1637675618&t=b08db257dc922b94f3f53ed8618845fbf19a1730}}
{Track_Num:4 Title:Isblod Streaming_URL:{MP3_128:https://bandcamp.com/stream_redirect?enc=mp3-128&track_id=357558696&ts=1637675618&t=c65b7620866e216828de006a9cd4d21028aebf1c}}
{Track_Num:5 Title:Dunkelstorm Streaming_URL:{MP3_128:https://bandcamp.com/stream_redirect?enc=mp3-128&track_id=194355283&ts=1637675618&t=ef1afe5e1dcec2fb531e37639fe2067aa2ddcfc8}}
{Track_Num:6 Title:Askevind Streaming_URL:{MP3_128:https://bandcamp.com/stream_redirect?enc=mp3-128&track_id=3905939791&ts=1637675618&t=286c654e71a6c78b336f4852cea06cedd1f28e46}}
~~~

https://github.com/89z/mech

**Comment by nrlquaker** [comment]
It was a wrong path in `--base-dir` in alias.
