### ISSUE TITLE
Downloading doesn't work (TypeError: 'NoneType' object is not subscriptable)

### ISSUE THREAD

**Issue by Kilkenni** [Evolution0/bandcamp-dl#204]
**To Reproduce**
Command to reproduce the behavior:
`bandcamp-dl --embed-art URL https://curtisschweitzer.bandcamp.com/album/staxel-volume-0 -d`
```
[URL or List of URLs HERE](https://curtisschweitzer.bandcamp.com/album/staxel-volume-0)
```

**Expected behavior**
Downloading in the current directory.

**Logs**
```
DEBUG:root:
	URL: URL
DEBUG:root:
	URL: https://curtisschweitzer.bandcamp.com/album/staxel-volume-0
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): curtisschweitzer.bandcamp.com:443
DEBUG:urllib3.connectionpool:https://curtisschweitzer.bandcamp.com:443 "GET /album/staxel-volume-0 HTTP/1.1" 200 None
DEBUG:root: Generating BandcampJSON..
DEBUG:root: Grab pagedata JSON..
DEBUG:root: Grabbing embedded scripts..
DEBUG:root: Converting JS to JSON..
DEBUG:root: Converting JS to JSON..
DEBUG:root: BandcampJSON generated..
DEBUG:root: Generating Album..
DEBUG:root: Generating track metadata..
DEBUG:root: Track metadata generated..
DEBUG:root: Generating track metadata..
DEBUG:root: Track metadata generated..
DEBUG:root: Generating track metadata..
DEBUG:root: Track metadata generated..
DEBUG:root: Generating track metadata..
DEBUG:root: Track metadata generated..
DEBUG:root: Generating track metadata..
DEBUG:root: Track metadata generated..
DEBUG:root: Generating track metadata..
DEBUG:root: Track metadata generated..
DEBUG:root: Generating track metadata..
DEBUG:root: Track metadata generated..
DEBUG:root: Generating track metadata..
DEBUG:root: Track metadata generated..
DEBUG:root: Generating track metadata..
DEBUG:root: Track metadata generated..
DEBUG:root: Generating track metadata..
DEBUG:root: Track metadata generated..
DEBUG:root: Generating track metadata..
DEBUG:root: Track metadata generated..
DEBUG:root: Generating track metadata..
DEBUG:root: Track metadata generated..
DEBUG:root: Album generated..
DEBUG:root: Album URL: https://curtisschweitzer.bandcamp.com/album/staxel-volume-0
DEBUG:root: Album data:
	None
DEBUG:root: Album data:
	{'tracks': [{'duration': 234.667, 'track': '1', 'title': 'In Town', 'url': 'https://t4.bcbits.com/stream/b8eb3f13b82770d504f9817457934e59/mp3-128/2475259724?p=0&ts=1676191103&t=797aa34444c8d07fc5ae926421786895b5c64f21&token=1676191103_2d0548ea1001e1e45a09b0dd8179793c7d65e0e0'}, {'duration': 228.293, 'track': '2', 'title': 'Gardens', 'url': 'https://t4.bcbits.com/stream/c4106cd75f7f2fe8c15a55223f102d16/mp3-128/2640076435?p=0&ts=1676191103&t=d40d32d1854b25e06bc7039c3adde0a5f2a97363&token=1676191103_3378cf65c64263d95325f9ec9d157a627102603d'}, {'duration': 198.5, 'track': '3', 'title': 'The Green Light', 'url': 'https://t4.bcbits.com/stream/f543fac2051d495bd4f689ad012c5761/mp3-128/1162095222?p=0&ts=1676191103&t=35aa62e29cf7fc4a1c8d442d4ac7ccf3def97eb5&token=1676191103_6e57086a770c61d6c6b30a7e122b45492d0a02b0'}, {'duration': 269.333, 'track': '4', 'title': 'Magic Hour', 'url': 'https://t4.bcbits.com/stream/ce6210a5d1d3a4c901cb73331641982f/mp3-128/3337815255?p=0&ts=1676191103&t=16fbdc87b533dc7a5ff1eb9d4bae9518834f1205&token=1676191103_538384506f71ee3e372c40f2c0e1e2c1cac7b9be'}, {'duration': 229.714, 'track': '5', 'title': 'Ether', 'url': 'https://t4.bcbits.com/stream/83fed5ba448e65add89b74984e50b8ec/mp3-128/2521414272?p=0&ts=1676191103&t=8f369ce3f3f7e33797361d204f2fa94b579ad50e&token=1676191103_b6aa95a4df0d550debcfe1f50ec568f11116d025'}, {'duration': 193.583, 'track': '6', 'title': 'Summer Solstice', 'url': 'https://t4.bcbits.com/stream/0959fb9fb795725832a5fe32fc8842bd/mp3-128/1601551348?p=0&ts=1676191103&t=0e8ae18a75904e3aa6a183fa8374073f323ebc48&token=1676191103_53e800e7f4667017d01fbb1eb99664fb62fe1128'}, {'duration': 202.204, 'track': '7', 'title': 'High Summer into Autumn', 'url': 'https://t4.bcbits.com/stream/62f4b01792e96fdaca5263b6ca090d87/mp3-128/2798608594?p=0&ts=1676191103&t=d77bcdb8ea2f89dcae8ba95885f6a660ff3e80dd&token=1676191103_33e03b59410869f9c8b7d55c810608637a768c70'}, {'duration': 186.4, 'track': '8', 'title': 'The Harvest', 'url': 'https://t4.bcbits.com/stream/98e25ff68505944cdaa12aaa370b0d73/mp3-128/3979280263?p=0&ts=1676191103&t=47c97c994caac64e8f456a4654a30180af1c93cf&token=1676191103_29e04dac7e59d455bc5400319a5e98d57fc8c4ff'}, {'duration': 216.0, 'track': '9', 'title': 'Winter Warmth', 'url': 'https://t4.bcbits.com/stream/9de16b02b900b3db208580515a543da9/mp3-128/2997490378?p=0&ts=1676191103&t=43b718b8eeb0a85ffefffa5c6c0f389662485374&token=1676191103_c6b35e14a633b64e0722601cca6056f25910fdf9'}, {'duration': 264.0, 'track': '10', 'title': 'Verdant', 'url': 'https://t4.bcbits.com/stream/332371db9a2ebf5c3edb20939f190c5a/mp3-128/1099104055?p=0&ts=1676191103&t=6468f54ba51fd1bd520fc907403dcb68081738ec&token=1676191103_30a407307654a2558cd0965d0e5ac7b505eb3862'}, {'duration': 180.0, 'track': '11', 'title': 'Noon', 'url': 'https://t4.bcbits.com/stream/225c3b462297c0bc861698ce7007b0d2/mp3-128/2929725406?p=0&ts=1676191103&t=5c897a49cd96b0b8e4d9daf21834bcb61758ec15&token=1676191103_f48325852506952a2750a71052a862c9cbf0791a'}, {'duration': 270.545, 'track': '12', 'title': 'Nocturne', 'url': 'https://t4.bcbits.com/stream/6ae4e8947b4ee475e7d16e789c8f6f4c/mp3-128/4132730059?p=0&ts=1676191103&t=33f3293057a2ffc850e6dd5678e0117fac9054c0&token=1676191103_a800e54a92e4198f4f7ec8e258586e36f917276a'}], 'title': 'Staxel Volume 0', 'artist': 'Curtis Schweitzer', 'label': 'Curtis Schweitzer', 'full': True, 'art': 'https://f4.bcbits.com/img/a1258872857_10.jpg', 'date': '2015', 'url': 'https://curtisschweitzer.bandcamp.com/album/staxel-volume-0'}
DEBUG:root:Preparing download process..
Traceback (most recent call last):
  File "/home/REDACTED/.local/bin/bandcamp-dl", line 8, in <module>
    sys.exit(main())
  File "/home/REDACTED/.local/lib/python3.10/site-packages/bandcamp_dl/__main__.py", line 123, in main
    arguments['--keep-upper'], arguments['--debug'], album['url'])
TypeError: 'NoneType' object is not subscriptable

```

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version 22.04.1 LTS
 - Python Version 3.10.16

**Comment by Kilkenni** [comment]
sorry, just me being stupid. It doesn't need "URL" string, only the actual URL.
