### ISSUE TITLE
Unable to download single tracks.

### ISSUE THREAD

**Issue by Unnoen** [Evolution0/bandcamp-dl#24]
The script is unable to download tracks, only full albums.

**Comment by iheanyi** [comment]
Eek. I'll have to revisit this. Sorry, my role on this has been stagnant and the community has been upgrading it, but I'll explore adding back in single track downloads. Sorry about that!

**Comment by Unnoen** [comment]
No problem, only found this recently. Better than any other script out there.

**Comment by iheanyi** [comment]
Still having this issue or nah? @Zegura

**Comment by iheanyi** [comment]
Still works for me. Re-open with specific examples please if you have them.

**Comment by amaramth** [comment]
specific example:

```
~ git clone git@github.com:iheanyi/bandcamp-dl.git
Cloning into 'bandcamp-dl'...
remote: Counting objects: 244, done.
remote: Total 244 (delta 0), reused 0 (delta 0), pack-reused 244
Receiving objects: 100% (244/244), 49.39 KiB | 0 bytes/s, done.
Resolving deltas: 100% (115/115), done.
Checking connectivity... done.
~ cd bandcamp-dl/bandcamp_dl/
~/bandcamp-dl/bandcamp_dl ./bandcamp_dl.py https://thel-train.bandcamp.com/track/a-symphonic-metal-tribute-to-frozen
Traceback (most recent call last):
  File "./bandcamp_dl.py", line 67, in <module>
    main()
  File "./bandcamp_dl.py", line 55, in main
    album = bandcamp.parse(url)
  File "/Users/ali/bandcamp-dl/bandcamp_dl/Bandcamp.py", line 28, in parse
    album_meta = self.extract_album_meta_data(r)
  File "/Users/ali/bandcamp-dl/bandcamp_dl/Bandcamp.py", line 76, in extract_album_meta_data
    album['title'] = embedData['EmbedData']['album_title']
KeyError: 'album_title'
~/bandcamp-dl/bandcamp_dl ./bandcamp_dl.py https://thel-train.bandcamp.com/album/moonrise
Starting download process.
  52 % [===========>           ]   1.6MiB /  3.0MiB   52.1KiB/s  eta 0:00:28   
```

**Comment by iheanyi** [comment]
Thanks @alice0meta, I appreciate it! I'll take a look at this.

**Comment by iheanyi** [comment]
@alice0meta - I've added in a fix with this commit: https://github.com/iheanyi/bandcamp-dl/commit/ac7dea2fecba0bf0453f25d02380bcb7e9e44d95. Pull and try again and let me know if your problem is solved. Thanks!

**Comment by amaramth** [comment]
Yeah, that works. Thanks.

**Comment by iheanyi** [comment]
@alice0meta - No problem!

**Comment by brandonkeene** [comment]
Hi @iheanyi 
I'm actually seeing the same issue after a fresh install today. Downloading albums works flawlessly, however single tracks throw the same error seen above.  Here's some specifics for you:

```
blk@Tower ~ $ bandcamp-dl https://blackflower1.bandcamp.com/track/dust
Traceback (most recent call last):
  File "/usr/local/bin/bandcamp-dl", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/dist-packages/bandcamp_dl/bandcamp_dl.py", line 55, in main
    album = bandcamp.parse(url)
  File "/usr/local/lib/python2.7/dist-packages/bandcamp_dl/Bandcamp.py", line 28, in parse
    album_meta = self.extract_album_meta_data(r)
  File "/usr/local/lib/python2.7/dist-packages/bandcamp_dl/Bandcamp.py", line 76, in extract_album_meta_data
    album['title'] = embedData['EmbedData']['album_title']
KeyError: 'album_title'
```

Pip Version:

```
blk@Tower ~ $ pip -V
pip 8.1.2 from /usr/local/lib/python2.7/dist-packages (python 2.7)
```

Python Version:

```
blk@Tower ~ $ python2.7 -V
Python 2.7.12
```

Am I missing something obvious?
Thanks!
