### ISSUE TITLE
FileNotFoundError - No such file or directory - bandcamp-dl.json

### ISSUE THREAD

**Issue by ENiGMATiiQ** [Evolution0/bandcamp-dl#240]
**Describe the bug**
Fails to start program for any url, says missing json file at user folder

**To Reproduce**
Command to reproduce the behavior:
`bandcamp-dl <URL>`

**Expected behavior**
Downloader runs

**Logs**
```
PS C:\Users\Brad> bandcamp-dl --debug <URL>
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\Brad\AppData\Local\Programs\Python\Python312\Scripts\bandcamp-dl.exe\__main__.py", line 7, in <module>
  File "C:\Users\Brad\AppData\Local\Programs\Python\Python312\Lib\site-packages\bandcamp_dl\__main__.py", line 34, in main
    conf = config.Config()
           ^^^^^^^^^^^^^^^
  File "C:\Users\Brad\AppData\Local\Programs\Python\Python312\Lib\site-packages\bandcamp_dl\config.py", line 44, in __init__
    self._read_write_config()
  File "C:\Users\Brad\AppData\Local\Programs\Python\Python312\Lib\site-packages\bandcamp_dl\config.py", line 60, in _read_write_config
    with pathlib.Path.open(CONFIG_PATH, mode="w") as fobj:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Brad\AppData\Local\Programs\Python\Python312\Lib\pathlib.py", line 1013, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Brad\\.bandcamp-dl\\bandcamp-dl.json'
```

**Desktop (please complete the following information):**
 - OS: Windows
 - Version Windows 11 23H2 22631.4249
 - Python Version 3.12.6

**Additional context**
Bug present on multiple fresh install attempts across multiple user accounts and on other PCs with fresh Python installs

**Comment by sfredo** [comment]
had a similar error:

`FileNotFoundError: [Errno 2] No such file or directory: '/Users/USERNAME/.config/bandcamp-dl.json'
`

that was resolved by creating the `.config` folder, yours could be resolved by creating the `.bandcamp-dl` folder in `C:\\Users\\Brad\\`

**Comment by ENiGMATiiQ** [comment]
> had a similar error:
> 
> `FileNotFoundError: [Errno 2] No such file or directory: '/Users/USERNAME/.config/bandcamp-dl.json' `
> 
> that was resolved by creating the `.config` folder, yours could be resolved by creating the `.bandcamp-dl` folder in `C:\\Users\\Brad\\`

This resolved it, thanks!

**Comment by ojinikaudeze** [comment]
Hi there, I think I am having a similar error here. ```
`Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.13/bin/bandcamp-dl", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/bandcamp_dl/__main__.py", line 34, in main
    conf = config.Config()
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/bandcamp_dl/config.py", line 44, in __init__
    self._read_write_config()
    ~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/site-packages/bandcamp_dl/config.py", line 60, in _read_write_config
    with pathlib.Path.open(CONFIG_PATH, mode="w") as fobj:
         ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.13/lib/python3.13/pathlib/_local.py", line 537, in open
    return io.open(self, mode, buffering, encoding, errors, newline)
           ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/Users/ojinika/.config/bandcamp-dl.json'`
``` 

please help

**Comment by Evolution0** [comment]
Not solved as the directories should be created if they don't exist automatically.

**Comment by ojinikaudeze** [comment]
Sorry I deleted my comment as I created a new ticket. Please advise.

**Comment by Suburbanno** [comment]
> had a similar error:
> 
> `FileNotFoundError: [Errno 2] No such file or directory: '/Users/USERNAME/.config/bandcamp-dl.json' `
> 
> that was resolved by creating the `.config` folder, yours could be resolved by creating the `.bandcamp-dl` folder in `C:\\Users\\Brad\\`

worked for me, thanks
