### ISSUE TITLE
ModuleNotFoundError: No module named 'tomllib'

### ISSUE THREAD

**Issue by aaroncommand** [Evolution0/bandcamp-dl#241]
**Describe the bug**

bandcamp-dl exits with a stack trace, regardless of any arguments passed.
This appears to be due to the fact that the tomllib library was introduced with Python 3.11, which is not installed on Linux Mint 21.3 and other distros.

**To Reproduce**

$ bandcamp-dl
Traceback (most recent call last):
  File "/home/apatters/.local/bin/bandcamp-dl", line 5, in <module>
    from bandcamp_dl.__main__ import main
  File "/home/apatters/.local/pipx/venvs/bandcamp-downloader/lib/python3.10/site-packages/bandcamp_dl/__init__.py", line 3, in <module>
    import tomllib
ModuleNotFoundError: No module named 'tomllib'

**Desktop (please complete the following information):**

 - OS: Linux Mint 21.3

$ python3 --version
Python 3.10.12

Thanks!

**Comment by Evolution0** [comment]
Pushed what I hope will be a fix, can't really test right now but you should be able to pull the master branch and build it.

**Comment by pluv1a** [comment]
Update your python to at least 3.11 to support `tomllib`.

**Comment by Evolution0** [comment]
Should have been fixed in: evolution0@7154b52872ff0ffe09b47e4f33034d50fc0606bb
