### ISSUE TITLE
Python error on Embed album art if file exists

### ISSUE THREAD

**Issue by nilsbyte** [Evolution0/bandcamp-dl#244]
**Describe the bug**
When trying to download existing (already downloaded) tracks with the 'Embed album art' option enabled, a Python error occurs.

**To Reproduce**
Command to reproduce the behavior:
`bandcamp-dl https://stphanepicq.bandcamp.com/track/dune-theme-2024-remaster-original-speed -d -r -y --base-dir=/Users/usernamehere/Desktop/BandcampDL-TEST --template="%{artist} - %{album}/%{artist} - %{title}"`
```
https://stphanepicq.bandcamp.com/track/dune-theme-2024-remaster-original-speed
```

**Expected behavior**
Album art of the track should be embedded, bandcamp-dl should not crash

**Logs**
Most if not always you will get some kind of output explaining the issue, post it:
```
nils@MBP-von-Nils ~ % bandcamp-dl https://stphanepicq.bandcamp.com/track/dune-theme-2024-remaster-original-speed -d -r -y --base-dir=/Users/nils/Desktop/BandcampDL-TEST --template="%{artist} - %{album}/%{artist} - %{title}"
DEBUG:bandcamp-dl:Config/Args: Namespace(URL=['https://stphanepicq.bandcamp.com/track/dune-theme-2024-remaster-original-speed'], version=False, debug=True, artist=None, track=None, album=None, template='%{artist} - %{album}/%{artist} - %{title}', base_dir='/Users/nils/Desktop/BandcampDL-TEST', full_album=False, overwrite=False, no_art=False, embed_lyrics=False, group=False, embed_art=True, no_slugify=True, ok_chars='-_~', space_char='-', ascii_only=False, keep_spaces=False, keep_upper=False, no_confirm=False)
DEBUG:bandcamp-dl:
	URL: https://stphanepicq.bandcamp.com/track/dune-theme-2024-remaster-original-speed
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): stphanepicq.bandcamp.com:443
DEBUG:urllib3.connectionpool:https://stphanepicq.bandcamp.com:443 "GET /track/dune-theme-2024-remaster-original-speed HTTP/11" 200 None
DEBUG:bandcamp-dl.Main: Generating BandcampJSON..
DEBUG:bandcamp-dl.JSON: Grab pagedata JSON..
DEBUG:bandcamp-dl.JSON: Grabbing embedded scripts..
DEBUG:bandcamp-dl.JSON: Converting JS to JSON..
DEBUG:bandcamp-dl.JSON: Converting JS to JSON..
DEBUG:bandcamp-dl.Main: BandcampJSON generated..
DEBUG:bandcamp-dl.Main: Generating Album..
DEBUG:bandcamp-dl.Main: Generating track metadata..
DEBUG:bandcamp-dl.Main: Track metadata generated..
DEBUG:bandcamp-dl.Main: Album generated..
DEBUG:bandcamp-dl.Main: Album URL: https://stphanepicq.bandcamp.com/track/dune-theme-2024-remaster-original-speed
DEBUG:bandcamp-dl: Album data:
	{'tracks': [{'duration': 309.68, 'track': '1', 'title': 'Stéphane Picq - Dune Theme [2024 remaster] (original speed)', 'artist': 'Stéphane Picq', 'url': 'https://t4.bcbits.com/stream/03ae271ae25b347ff0a998ab76b24b1a/mp3-128/836974923?p=0&ts=1732832556&t=4cc11e29accb57fe90c144ef53a6551b725692a0&token=1732832556_8f5116f5d27ed024a4caacb102e89fd82d9de57d'}], 'title': 'Dune Theme [2024 remaster] (original speed)', 'artist': 'Stéphane Picq', 'label': 'Stéphane Picq', 'full': True, 'art': 'https://f4.bcbits.com/img/a1516700930_10.jpg', 'date': '2024', 'url': 'https://stphanepicq.bandcamp.com/track/dune-theme-2024-remaster-original-speed'}
DEBUG:bandcamp-dl:Preparing download process..
DEBUG:bandcamp-dl:Initiating download process..
DEBUG:bandcamp-dl.Downloader: Generating filepath/trackname..
DEBUG:bandcamp-dl.Downloader:
	Template: %{artist} - %{album}/%{artist} - %{title}
DEBUG:bandcamp-dl.Downloader:Track artist is not None
DEBUG:bandcamp-dl.Downloader: filepath/trackname generated..
DEBUG:bandcamp-dl.Downloader:
	Path: /Users/nils/Desktop/BandcampDL-TEST/Stéphane Picq - Dune Theme [2024 remaster] (original speed)/Stéphane Picq - Dune Theme [2024 remaster] (original speed).mp3
DEBUG:bandcamp-dl.Downloader: Directory:
	/Users/nils/Desktop/BandcampDL-TEST/Stéphane Picq - Dune Theme [2024 remaster] (original speed)
DEBUG:bandcamp-dl.Downloader: Directory doesn't exist, creating..
DEBUG:bandcamp-dl.Downloader: Current file:
	/Users/nils/Desktop/BandcampDL-TEST/Stéphane Picq - Dune Theme [2024 remaster] (original speed)/Stéphane Picq - Dune Theme [2024 remaster] (original speed).mp3.tmp
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): t4.bcbits.com:443
DEBUG:urllib3.connectionpool:https://t4.bcbits.com:443 "GET /stream/03ae271ae25b347ff0a998ab76b24b1a/mp3-128/836974923?p=0&ts=1732832556&t=4cc11e29accb57fe90c144ef53a6551b725692a0&token=1732832556_8f5116f5d27ed024a4caacb102e89fd82d9de57d HTTP/11" 200 4955741
File: Stéphane Picq - Dune Theme [2024 remaster] (original speed).mp3 already exists and is complete, skipping..
Traceback (most recent call last):
  File "/opt/homebrew/bin/bandcamp-dl", line 8, in <module>
    sys.exit(main())
             ~~~~^^
  File "/opt/homebrew/Cellar/bandcamp-dl/0.0.16_1/libexec/lib/python3.13/site-packages/bandcamp_dl/__main__.py", line 132, in main
    bandcamp_downloader.start(album)
    ~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/opt/homebrew/Cellar/bandcamp-dl/0.0.16_1/libexec/lib/python3.13/site-packages/bandcamp_dl/bandcampdownloader.py", line 52, in start
    self.download_album(album)
    ~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/opt/homebrew/Cellar/bandcamp-dl/0.0.16_1/libexec/lib/python3.13/site-packages/bandcamp_dl/bandcampdownloader.py", line 229, in download_album
    os.remove(self.album_art)
              ^^^^^^^^^^^^^^
AttributeError: 'BandcampDownloader' object has no attribute 'album_art'
```

If possible after running the command with the --debug option.

**Desktop (please complete the following information):**
 - OS: macOS 
 - Version 14.7.1
 - Python Version 3.9.6

**Comment by Evolution0** [comment]
TODO: Add if check for embeddable data args so that it grabs and embeds to existing downloads.
