### ISSUE TITLE
The url {} is not a valid bandcamp page

### ISSUE THREAD

**Issue by Klick3R** [Evolution0/bandcamp-dl#27]
Ok so i recently wanted to check this project out, now it should be pretty straight forward, when i run this command(or any other url for that matter):

```
python bandicamp-dl.py https://sdoggingsworth.bandcamp.com/album/snacks-hugs-and-rock-n-roll
```

i get the following error:

```
File "bandcamp-dl.py", line 60
    print "The url {} is not a valid bandcamp page.".format(url)

SyntaxError: invalid syntax
```

no matter what i try i cant figure out what is causing this, im running ArchLinux and i have tried with python 2&3

**Comment by Mail2274** [comment]
same problem occurring with me

**Comment by tmbr54** [comment]
Hey. I fixed this by using Python 2.7.10. I tried 3 at first, but I kept running in to the same error. I also had to do 'py-2 pip install ply==3.4' to get rid of another error. Might be late but googling the error only brings up this page :)

**Comment by ostrosablin** [comment]
It indeed doesn't work with ply 3.6, causes this:

```
Traceback (most recent call last):
  File "./bandcamp-dl.py", line 56, in <module>
    album = bandcamp.parse(url)
  File "Bandcamp.py", line 28, in parse
    album_meta = self.extract_album_meta_data(r)
  File "Bandcamp.py", line 67, in extract_album_meta_data
    embedData = self.get_embed_string_block(request)
  File "Bandcamp.py", line 100, in get_embed_string_block
    embedStringBlock = jsobj.read_js_object("var EmbedData = %s" % embedStringBlock)
  File "jsobj.py", line 71, in read_js_object
    return visit(Parser().parse(code))
  File "/usr/lib64/python2.7/site-packages/slimit/parser.py", line 56, in __init__
    self.lexer.build(optimize=lex_optimize, lextab=lextab)
  File "/usr/lib64/python2.7/site-packages/slimit/lexer.py", line 102, in build
    self.lexer = ply.lex.lex(object=self, **kwargs)
  File "/usr/lib64/python2.7/site-packages/ply/lex.py", line 897, in lex
    if '.' not in lextab:
TypeError: argument of type 'module' is not iterable
```

Downgrading ply to version 3.4 as suggesed above helps, though.

**Comment by cibulka** [comment]
As I am, by all means, no Python ninja - is this error caused by the same issue? 

```
WARNING: Couldn't write lextab module <module 'slimit.lextab' from '/usr/local/lib/python2.7/site-packages/slimit/lextab.pyc'>. Won't overwrite existing lextab module
WARNING: yacc table file version is out of date
WARNING: Token 'IMPORT' defined, but not used
WARNING: Token 'BLOCK_COMMENT' defined, but not used
WARNING: Token 'ENUM' defined, but not used
WARNING: Token 'EXTENDS' defined, but not used
WARNING: Token 'LINE_COMMENT' defined, but not used
WARNING: Token 'LINE_TERMINATOR' defined, but not used
WARNING: Token 'CONST' defined, but not used
WARNING: Token 'EXPORT' defined, but not used
WARNING: Token 'CLASS' defined, but not used
WARNING: Token 'SUPER' defined, but not used
WARNING: There are 10 unused tokens
WARNING: Couldn't create <module 'slimit.yacctab' from '/usr/local/lib/python2.7/site-packages/slimit/yacctab.pyc'>. Won't overwrite existing tabmodule
WARNING: Couldn't write lextab module <module 'slimit.lextab' from '/usr/local/lib/python2.7/site-packages/slimit/lextab.pyc'>. Won't overwrite existing lextab module
WARNING: yacc table file version is out of date
WARNING: Token 'IMPORT' defined, but not used
WARNING: Token 'BLOCK_COMMENT' defined, but not used
WARNING: Token 'ENUM' defined, but not used
WARNING: Token 'EXTENDS' defined, but not used
WARNING: Token 'LINE_COMMENT' defined, but not used
WARNING: Token 'LINE_TERMINATOR' defined, but not used
WARNING: Token 'CONST' defined, but not used
WARNING: Token 'EXPORT' defined, but not used
WARNING: Token 'CLASS' defined, but not used
WARNING: Token 'SUPER' defined, but not used
WARNING: There are 10 unused tokens
WARNING: Couldn't create <module 'slimit.yacctab' from '/usr/local/lib/python2.7/site-packages/slimit/yacctab.pyc'>. Won't overwrite existing tabmodule
unknown url type: //popplers5.bandcamp.com/download/track?enc=mp3-128&fsig=7618309861b92cf702a5d515150d05cb&id=972899220&stream=1&ts=1444865659.0
Downloading failed..
```

EDIT: I just saw I am duplicating https://github.com/iheanyi/bandcamp-dl/issues/26. Will downgrade Ply. Thank you!
