### ISSUE TITLE
TypeError: argument of type 'module' is not iterable and InsecurePlatformWarning

### ISSUE THREAD

**Issue by designingdesign** [Evolution0/bandcamp-dl#28]
from:
`python bandcamp-dl.py -f https://nicoledollanganger.bandcamp.com/album/greta-gibson-forever | --artist=nicoledollanganger --album=greta-gibson-forever`
I get this warning:

```
-bash: --artist=nicoledollanganger: command not found
/Library/Python/2.7/site-packages/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
Traceback (most recent call last):
  File "bandcamp-dl.py", line 56, in <module>
    album = bandcamp.parse(url)
  File "/Users/dd9000/Downloads/bandcamp-dl/Bandcamp.py", line 28, in parse
    album_meta = self.extract_album_meta_data(r)
  File "/Users/dd9000/Downloads/bandcamp-dl/Bandcamp.py", line 67, in extract_album_meta_data
    embedData = self.get_embed_string_block(request)
  File "/Users/dd9000/Downloads/bandcamp-dl/Bandcamp.py", line 100, in get_embed_string_block
    embedStringBlock = jsobj.read_js_object("var EmbedData = %s" % embedStringBlock)
  File "/Users/dd9000/Downloads/bandcamp-dl/jsobj.py", line 71, in read_js_object
    return visit(Parser().parse(code))
  File "/Library/Python/2.7/site-packages/slimit/parser.py", line 56, in __init__
    self.lexer.build(optimize=lex_optimize, lextab=lextab)
  File "/Library/Python/2.7/site-packages/slimit/lexer.py", line 102, in build
    self.lexer = ply.lex.lex(object=self, **kwargs)
  File "/Library/Python/2.7/site-packages/ply/lex.py", line 893, in lex
    if '.' not in lextab:
TypeError: argument of type 'module' is not iterable
```

OS X 10.10.3, Python 2.7.6

Looking up the InsecurePlatformWarning, I found [this page](http://stackoverflow.com/questions/29134512/insecureplatformwarning-a-true-sslcontext-object-is-not-available-this-prevent).

I still had the rest of the error message became:

```
Traceback (most recent call last):
  File "bandcamp-dl.py", line 56, in <module>
    album = bandcamp.parse(url)
  File "/Users/dd9000/Downloads/bandcamp-dl/Bandcamp.py", line 28, in parse
    album_meta = self.extract_album_meta_data(r)
  File "/Users/dd9000/Downloads/bandcamp-dl/Bandcamp.py", line 67, in extract_album_meta_data
    embedData = self.get_embed_string_block(request)
  File "/Users/dd9000/Downloads/bandcamp-dl/Bandcamp.py", line 100, in get_embed_string_block
    embedStringBlock = jsobj.read_js_object("var EmbedData = %s" % embedStringBlock)
  File "/Users/dd9000/Downloads/bandcamp-dl/jsobj.py", line 71, in read_js_object
    return visit(Parser().parse(code))
  File "/Library/Python/2.7/site-packages/slimit/parser.py", line 56, in __init__
    self.lexer.build(optimize=lex_optimize, lextab=lextab)
  File "/Library/Python/2.7/site-packages/slimit/lexer.py", line 102, in build
    self.lexer = ply.lex.lex(object=self, **kwargs)
  File "/Library/Python/2.7/site-packages/ply/lex.py", line 893, in lex
    if '.' not in lextab:
TypeError: argument of type 'module' is not iterable
```

**Comment by ColemanGariety** [comment]
+1

**Comment by ColemanGariety** [comment]
@designingdesign dupe of #26. A hack to fix it is in there, but this shouldn't happen.

**Comment by iheanyi** [comment]
Fixed this recently.
