### ISSUE TITLE
Error downloading single track. KeyError: 'album_title'

### ISSUE THREAD

**Issue by berrythesoftwarecodeprogrammar** [Evolution0/bandcamp-dl#46]
```
C:\>bandcamp-dl https://yunggemmy.bandcamp.com/track/cutest-in-the-game
Traceback (most recent call last):
  File "C:\Python27\Scripts\bandcamp-dl-script.py", line 9, in <module>
    load_entry_point('bandcamp-downloader==0.0.3', 'console_scripts', 'bandcamp-dl')()
  File "C:\Python27\lib\site-packages\bandcamp_dl\bandcamp_dl.py", line 55, in main
    album = bandcamp.parse(url)
  File "C:\Python27\lib\site-packages\bandcamp_dl\Bandcamp.py", line 28, in parse
    album_meta = self.extract_album_meta_data(r)
  File "C:\Python27\lib\site-packages\bandcamp_dl\Bandcamp.py", line 76, in extract_album_meta_data
    album['title'] = embedData['EmbedData']['album_title']
KeyError: 'album_title'
```

i read the instructions for submitting an issue but there was no --verbose argument available and -v only displayed the version.

im guessing its failing because im trying to download a track, not an album? this track doesnt belong to any album

Windows 7 x64
Python 2.7.10
EDIT: was using bandcamp-dl version from pip

**Comment by berrythesoftwarecodeprogrammar** [comment]
oops, as i was trying to overcome install errors, i installed the pip version on top of the git version so i was using an old one. i installed the git version again and it works fine
