### ISSUE TITLE
Downloading stopped to work

### ISSUE THREAD

**Issue by ostrosablin** [Evolution0/bandcamp-dl#61]
I'm getting following error (changed JS EmbedData format?):

Traceback (most recent call last):
  File "./bandcamp_dl/bandcamp_dl.py", line 67, in <module>
    main()
  File "./bandcamp_dl/bandcamp_dl.py", line 55, in main
    album = bandcamp.parse(url)
  File "/home/administrator/BCRip/bandcamp-dl-master/bandcamp-dl/bandcamp_dl/Bandcamp.py", line 28, in parse
    album_meta = self.extract_album_meta_data(r)
  File "/home/administrator/BCRip/bandcamp-dl-master/bandcamp-dl/bandcamp_dl/Bandcamp.py", line 67, in extract_album_meta_data
    embedData = self.get_embed_string_block(request)
  File "/home/administrator/BCRip/bandcamp-dl-master/bandcamp-dl/bandcamp_dl/Bandcamp.py", line 102, in get_embed_string_block
    embedStringBlock = jsobj.read_js_object("var EmbedData = %s" % embedStringBlock)
  File "/home/administrator/BCRip/bandcamp-dl-master/bandcamp-dl/bandcamp_dl/jsobj.py", line 72, in read_js_object
    return visit(Parser().parse(code))
  File "/usr/lib64/python2.7/site-packages/slimit/parser.py", line 56, in **init**
    self.lexer.build(optimize=lex_optimize, lextab=lextab)
  File "/usr/lib64/python2.7/site-packages/slimit/lexer.py", line 102, in build
    self.lexer = ply.lex.lex(object=self, **kwargs)
  File "/usr/lib64/python2.7/site-packages/ply/lex.py", line 897, in lex
    if '.' not in lextab:
TypeError: argument of type 'module' is not iterable

**Comment by ostrosablin** [comment]
Sorry, that's duplicate of ply-3.4+ bug.
