### ISSUE TITLE
Cygwin install instructions

### ISSUE THREAD

**Issue by Lucas-C** [Evolution0/bandcamp-dl#67]
Hello,

First, thank you very much for this great tool !

I thought it may be handy to add install instructions for Cygwin, so there are the package I needed to install using [apt-cyg](//github.com/transcode-open/apt-cyg):
```
apt-cyg install libxml2-devel libiconv-devel libxslt-devel
```

Then I was able to `pip install bandcamp-downloader` without `gcc` crashing while `Running setup.py install for lxml`.

I still had to install the `requests` lib manually as it seems to be missing from you dependencies:
```
Traceback (most recent call last):
  File "/cygdrive/c/Users/admin/.local/bin/bandcamp-dl", line 9, in <module>
    load_entry_point('bandcamp-downloader==0.0.3', 'console_scripts', 'bandcamp-dl')()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 552, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2672, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2345, in load
    return self.resolve()
  File "/usr/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2351, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/cygdrive/c/Users/admin/.local/lib/python2.7/site-packages/bandcamp_dl/bandcamp_dl.py", line 42, in <module>
    from Bandcamp import Bandcamp
  File "/cygdrive/c/Users/admin/.local/lib/python2.7/site-packages/bandcamp_dl/Bandcamp.py", line 2, in <module>
    import requests
ImportError: No module named requests
```

**Comment by Evolution0** [comment]
I don't get why you would.

Its not as if Cygwin can't use it unless its installed _in_ Cygwin. Installing the traditional way still gives anything looking at the PATH access to it. As far as I know Cygwin appends the system PATH to its own.

Unless for some reason you prefer to build without using the Visual C++ Compiler for Python or the Visual C++ Build Tools.

But really the main modules you would need to build are already available as wheels at places like: http://www.lfd.uci.edu/~gohlke/pythonlibs/

Then its just a matter of: `pip install name-of-wheel.whl`

Not sure why it could not find `requests` though but it is indeed in requirements.txt as it should be.

Edit: I got the wrong idea before, yes this is useful for those who already have Cygwin and would like to build and install lxml themselves, otherwise grab the wheel from the link I provided and install it before installing bandcamp-dl.
